### PR TITLE
Error handler to catch all unhandled errors

### LINKED ISSUE #117: Catch error around Airtable requests
When something goes wrong with the airtable requests the error it's not catch but the backend api ends without returning a response. This leaves the frontend request in a pending state and no message is shown to the user.

### PR DESCRIPTION
**Pull request by trizin**
Fixes #117.

Changes proposed in this PR:

- Express error handler to catch all unhandled errors
- Airtable error messages - when updating & creating entries

Should we show the error message to the user for each error?

### CODE REVIEW

File: backend/utils/airtable/utils.js [hunk 1]
```diff
@@ -122,7 +122,12 @@ async function updateAirtableEntry(recordId, proposal, grantCompleted = false) {
     update["Minimum USD Requested"] = proposal.minUsdRequested;
 
   if (proposal.oneLiner) update["One Liner"] = proposal.oneLiner;
-  await base("Proposals").update(recordId, update);
+  try {
+    await base("Proposals").update(recordId, update);
```
Comment (KatunaNorbert) [inline backend/utils/airtable/utils.js:126]: I don't think a try catch block will work around async function, you should use `.then(error => ... throw error)`

Comment (trizin) [reply backend/utils/airtable/utils.js:126]: You're right but it should catch the error because of `await`
Example code snippet:

```js
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function error(){
    await sleep(3000)
    throw new Error('error')
}

async function catchError(){
    try {
        await error()
    } catch (e) {
        console.log("Error happned:",e)
    }
}

catchError()
```

Comment (KatunaNorbert) [reply backend/utils/airtable/utils.js:126]: When I tested it, it didn't work. Maybe it's something related with the way Airtable throws the error. But if you tested it and it worked it's fine

Comment (trizin) [reply backend/utils/airtable/utils.js:126]: image

Comment (KatunaNorbert) [reply backend/utils/airtable/utils.js:126]: Ok, I'll approve

**Review by KatunaNorbert — APPROVED** [review]

File: backend/app.js [hunk 2]
```diff
@@ -26,15 +26,14 @@ app.use(function (req, res, next) {
...
+app.use(function (err, req, res, next) {
   // set locals, only providing error in development
   res.locals.message = err.message;
-  res.locals.error = req.app.get("env") === "development" ? err : {};
   console.error(err.message);
 
   // render the error page
   res.status(err.status || 500);
-  res.send("error");
+  res.json({ error: err.message });
```
Comment (idiom-bytes) [inline backend/app.js:36]: Thank you!

File: backend/utils/airtable/utils.js [hunk 3]
```diff
@@ -175,7 +180,14 @@ async function createAirtableEntry({
       "[ ] " + NodeHtmlMarkdown.NodeHtmlMarkdown.translate(grantDeliverables),
   };
 
-  const id = await base("Proposals").create(proposal);
+  let id;
+  try {
+    id = await base("Proposals").create(proposal);
+  } catch (err) {
+    console.error(err);
+    throw new Error("An error occurred while creating the Airtable entry");
```
Comment (idiom-bytes) [inline backend/utils/airtable/utils.js:188]: :cry: beautiful

**Review by idiom-bytes — APPROVED** [review]
Looks great!
