### PR TITLE
Earmark options selections fixes and improvements

### LINKED ISSUE #101: Update earmark dropdown menu, so that it defaults to the right earmark and shows other earmarks that proposals can select.
### Problem:
Many users were confused by the earmark select drop-down menu. Most of the time this is showing "General" or "Core-Tech" although the project is new and might have been assigned a separate earmark like "New Entrant"

## DoD:
- [ ] Proposals should have the correct default earmark selected
- [ ] Proposals that are new or fall within other earmark eligibility, should have those earmarks show up and be selected

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #101 #132
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/216

### CODE REVIEW

**Comment by idiom-bytes** [comment]
Push this one first, before the updates to error handling/validating the form.

**Comment by idiom-bytes** [comment]
Merged development and updated topic function to return the same results as [pr pr pr project - Round 21](https://port.oceanprotocol.com/t/pr-pr-pr-project-pol-pol-pole-round-21/1778)

File: backend/utils/discourse/utils.js [hunk 1]
```diff
@@ -17,27 +17,16 @@ function getMarkdown(project, proposal) {
...
-  );
   md.push({
     title: "# Proposal Earmark",
     body: earmarkJson[proposal.proposalEarmark],
   });
-  md.push({
-    title: "# Proposal Title",
-    body: proposal.oneLiner,
-  });
-
```
Comment (idiom-bytes) [inline backend/utils/discourse/utils.js]: Proposal Title / Proposal One Liner, is not used in the discourse post anymore.
https://port.oceanprotocol.com/t/pr-pr-pr-project-pol-pol-pole-round-21/1778

File: backend/utils/discourse/utils.js [hunk 2]
```diff
@@ -17,27 +17,16 @@ function getMarkdown(project, proposal) {
     title: "# Project Category",
     body: categoryJson[project.projectCategory],
   });
-  console.log(
-    proposal.proposalEarmark,
-    earmarkJson,
-    earmarkJson[proposal.proposalEarmark]
-  );
```
Comment (idiom-bytes) [inline backend/utils/discourse/utils.js]: disabled console log

File: backend/utils/discourse/utils.js [hunk 3]
```diff
@@ -17,27 +17,16 @@ function getMarkdown(project, proposal) {
...
   });
-  md.push({
-    title: "# Proposal Title",
-    body: proposal.oneLiner,
-  });
-
   if (proposal.proposalDescription)
     md.push({
-      title: "# Description",
+      title: "# Proposal Description",
```
Comment (idiom-bytes) [inline backend/utils/discourse/utils.js:26]: Updated this according to 
https://port.oceanprotocol.com/t/pr-pr-pr-project-pol-pol-pole-round-21/1778

File: frontend/src/utils/config.js [hunk 4]
```diff
@@ -1,4 +1,4 @@
 // Setup DEV/PROD env configurations.
 // You need to use "http://localhost:3005" as local if you are developing
-export const SERVER_URI = "http://localhost:3005";
+export const SERVER_URI = "";
```
Comment (idiom-bytes) [inline frontend/src/utils/config.js:3]: Reverted local configuration

**Review by idiom-bytes — APPROVED** [review]
I think this looks good.
