### PR TITLE
Fix current round not found

### LINKED ISSUE #58: Fix/Improve handling for get Current Round.
Fix current round not found bug: last round = the round with latest 'round starts' , active round = voting not started & round started

### PR DESCRIPTION
**Pull request by trizin**
Fixes #58 .

Changes proposed in this PR:

- Fix current round not found bug: last round = the round with latest 'round starts' , active round = voting not started & round started
- Submit the proposal for the next round if the due diligence period started.

### CODE REVIEW

File: backend/routes/project.js [hunk 1]
```diff
@@ -104,22 +110,25 @@ router.post(
     }
 
     const minUsdRequested = parseFloat(proposal.minUsdRequested);
+    if (!minUsdRequested) {
+      return res.status(400).json({
+        error: "Please enter a minimum USD amount",
```
Comment (idiom-bytes) [inline backend/routes/project.js:115]: Nice Catch

File: backend/routes/project.js [hunk 2]
```diff
@@ -66,6 +67,11 @@ router.post(
     const projectName = project.projectName;
 
     proposal.signer = res.locals.signer; // signer
+    if (processing.includes(proposal.signer)) {
+      res.status(400).send("Please try again later");
```
Comment (idiom-bytes) [inline backend/routes/project.js:71]: Looking at the logic... this looks like a backoff so that if the signer can't make more than 2 requests at the same time. 

Unsure if this is a kosher implementation for the problem but this seems like a simple and clean solution. Great!

File: backend/routes/project.js [hunk 3]
```diff
@@ -104,22 +110,25 @@ router.post(
...
+    let currentRoundNumber = currentRound.fields["Round"];
     const currentRoundSubmissionDeadline =
       currentRound.fields["Proposals Due By"];
 
     // if submission deadline has passed, return error
     if (Date.now() > new Date(currentRoundSubmissionDeadline).getTime()) {
-      return res.status(400).json({
-        error: "Submission deadline for this round has passed",
-      });
+      currentRoundNumber += 1; // submit proposal for next round
```
Comment (idiom-bytes) [inline backend/routes/project.js:131]: Awesome!

File: backend/routes/proposal.js [hunk 4]
```diff
@@ -85,8 +86,17 @@ router.post("/update", recaptchaCheck(0.5), checkSigner, function (req, res) {
       if (proposal.minUsdRequested)
         proposal.minUsdRequested = parseFloat(proposal.minUsdRequested);
 
-      const currentRound = await getCurrentRoundNumber();
-      if (data.round != currentRound) {
+      const currentRound = await getCurrentRound();
+      if (currentRound.fields["Round"] > data.round) {
+        return res
+          .status(400)
+          .json({ error: "You cannot update proposals in the past" });
```
Comment (idiom-bytes) [inline backend/routes/proposal.js:93]: Beautiful.

File: backend/routes/proposal.js [hunk 5]
```diff
@@ -180,6 +190,11 @@ router.post("/deliver", checkSigner, async (req, res) => {
           .status(400)
           .json({ error: "Proposal has already been delivered" });
 
+      const proposalInfo = await getProposalByRecordId(data.airtableRecordId);
+      if (proposalInfo.fields["Proposal State"] !== "Funded") {
```
Comment (idiom-bytes) [inline backend/routes/proposal.js:194]: The check we were looking for. Fantastic!

File: backend/utils/airtable/utils.js [hunk 6]
```diff
@@ -80,7 +81,7 @@ async function getCurrentRoundNumber() {
 async function getCurrentRound() {
   const nowDateString = new Date().toISOString();
   const roundParameters = await _getFundingRoundsSelectQuery(
-    `AND({Start Date} <= "${nowDateString}",{Voting Starts} > "${nowDateString}", "true")`
+    `AND({Start Date} < "${nowDateString}", "true")`
```
Comment (idiom-bytes) [inline backend/utils/airtable/utils.js:84]: Thank you! :+1: 

Explaining to myself as there are no comments. In this case, we should be expecting a few rows and it should not matter because we'll take [0] index. As we create rounds in-order, this should always work.

**Review by idiom-bytes — APPROVED** [review]
Looks great, I'm going to look through various tickets and verifications we have so we can expand on the tests that were done here.

I understand most of the work was done on the BE, so we'll make sure that these are reflected in the FE.

**Comment by idiom-bytes** [comment]
Looks great!
